apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: microservices
data:
  order-service.rego: |
    package orderservice

    import input

    # Default deny all requests
    default allow = false

    # Allow GET requests from product-service
    allow if {
        input.method == "GET"
        input.source == "product-service"
    }

    # Allow POST requests with valid order data from product-service
    allow if {
        input.method == "POST"
        input.source == "product-service"
        valid_order
    }

    # Define what constitutes a valid order
    valid_order if {
        input.request.product_id
        input.request.quantity > 0
    }

  product-service.rego: |
    package productservice

    import input

    # Default deny all requests
    default allow = false

    # Allow GET requests from any service
    allow if {
        input.method == "GET"
    }

    # Allow POST, PUT, DELETE requests only from order-service
    allow if {
        input.method in ["POST", "PUT", "DELETE"]
        input.source == "order-service"
    }

    # Rate limiting: allow if fewer than 100 requests in the last minute
    allow if {
        count(input.requests_last_minute) < 100
    }