apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: microservices
  labels:
    app: opa
spec:
  selector:
    app: opa
  ports:
  - port: 8181
    targetPort: 8181
    name: http
  type: ClusterIP