# Simplified APISIX configuration
gateway:
  type: NodePort
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

admin:
  enabled: true
  credentials:
    admin: aDm1n
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

dashboard:
  enabled: false  # Disable dashboard to save resources

etcd:
  enabled: false  # Use built-in etcd mode
  
standalone:
  enabled: true  # Use standalone mode (no external etcd)

# Reduce resource usage
apisix:
  enableIPv6: false
  luaModuleHook: 
    enabled: false

global:
  enabled: false