apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
  labels:
    app: product-service
    monitoring: "true"
spec:
  selector:
    app: product-service
  ports:
  - port: 8000
    targetPort: 80 #product-service container is configured to expose port 8000, but Nginx is only listening on port 80.
    name: http
  type: ClusterIP #changed from LoadBalancer