apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
  labels:
    app: product-service
    monitoring: "true"
spec:
  selector:
    app: product-service
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer #changed from ClusterIp