apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
    monitoring: "true"
spec:
  selector:
    app: order-service
  ports:
  - port: 8000
    targetPort: 80
    name: http
  type: ClusterIP