apiVersion: v1
data:
  config.yaml: |-
    # log options
    log_level: "info"
    log_output: "stderr"
    cert_file: "/etc/webhook/certs/cert.pem"
    key_file: "/etc/webhook/certs/key.pem"
    http_listen: ":8080"
    https_listen: ":8443"
    ingress_publish_service: ""
    enable_profiling: true
    apisix_resource_sync_interval: 1h
    plugin_metadata_cm: ""
    kubernetes:
      kubeconfig: ""
      resync_interval: "6h"
      namespace_selector:
      - ""
      election_id: "ingress-apisix-leader"
      ingress_class: "apisix"
      ingress_version: "networking/v1"
      watch_endpointslices: false
      apisix_route_version: "apisix.apache.org/v2"
      enable_gateway_api: false
      apisix_version: "apisix.apache.org/v2"
    apisix:
      admin_api_version: "v3"
      default_cluster_base_url: "http://apisix-admin.microservices.svc.cluster.local:9180/apisix/admin"
      default_cluster_admin_key: "edd1c9f034335f136f87ad84b625c8f1"
      default_cluster_name: "default"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"# log options\nlog_level: \"info\"\nlog_output: \"stderr\"\ncert_file: \"/etc/webhook/certs/cert.pem\"\nkey_file: \"/etc/webhook/certs/key.pem\"\nhttp_listen: \":8080\"\nhttps_listen: \":8443\"\ningress_publish_service: \"\"\nenable_profiling: true\napisix_resource_sync_interval: 1h\nplugin_metadata_cm: \"\"\nkubernetes:\n  kubeconfig: \"\"\n  resync_interval: \"6h\"\n  namespace_selector:\n  - \"\"\n  election_id: \"ingress-apisix-leader\"\n  ingress_class: \"apisix\"\n  ingress_version: \"networking/v1\"\n  watch_endpointslices: false\n  apisix_route_version: \"apisix.apache.org/v2\"\n  enable_gateway_api: false\n  apisix_version: \"apisix.apache.org/v2\"\napisix:\n  admin_api_version: \"v3\"\n  default_cluster_base_url: \"http://apisix-admin.ingress-apisix.svc.cluster.local:9180/apisix/admin\"\n  default_cluster_admin_key: \"edd1c9f034335f136f87ad84b625c8f1\"\n  default_cluster_name: \"default\""},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"apisix","meta.helm.sh/release-namespace":"microservices"},"creationTimestamp":"2025-02-22T12:06:30Z","labels":{"app.kubernetes.io/instance":"apisix","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ingress-controller","app.kubernetes.io/version":"1.8.0","helm.sh/chart":"ingress-controller-0.14.0"},"name":"apisix-configmap","namespace":"microservices","resourceVersion":"944153","uid":"b01bdf5b-19fb-4dc9-b79e-d75c61801eb3"}}
    meta.helm.sh/release-name: apisix
    meta.helm.sh/release-namespace: microservices
  creationTimestamp: "2025-02-22T12:06:30Z"
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-controller
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: ingress-controller-0.14.0
  name: apisix-configmap
  namespace: microservices
  resourceVersion: "953188"
  uid: b01bdf5b-19fb-4dc9-b79e-d75c61801eb3
