apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: product-test-route
  namespace: microservices
spec:
  http:
  - name: product-test
    match:
      hosts:
      - "api.example.com"
      paths:
      - /products
    backends:
    - serviceName: product-service
      servicePort: 80

