apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: microservices-routes
  namespace: microservices
spec:
  http:
  - name: product-service-route
    match:
      hosts:
      - api.example.com #formerly "api.microservices.local"
      paths:
      - /products*
    backends:
    - serviceName: product-service
      servicePort: 80 #changed from port 8000
    plugins:
    - name: cors
      enable: true
      config:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Authorization,Content-Type,Accept,X-API-Key"
        max_age: 3600
    - name: prometheus
      enable: true
    - name: response-rewrite
      enable: true
      config:
        headers:
          add:
            X-Gateway: APISIX
            X-Service: product-service
  
  - name: order-service-route
    match:
      hosts:
      - api.example.com #formerly api.microservices.local
      paths:
      - /orders*
    backends:
    - serviceName: order-service
      servicePort: 8000
    plugins:
    - name: cors
      enable: true
      config:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Authorization,Content-Type,Accept,X-API-Key"
        max_age: 3600
    - name: prometheus
      enable: true
    - name: response-rewrite
      enable: true
      config:
        headers:
          add:
            X-Gateway: APISIX
            X-Service: order-service
    
  - name: health-route
    match:
      hosts:
      - api.microservices.local
      paths:
      - /health
    backends:
    - serviceName: product-service
      servicePort: 80
      weight: 100
    - serviceName: order-service
      servicePort: 8000
      weight: 100
    plugins:
    - name: prometheus
      enable: true