apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir0-yb-master-0
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # This should match the PV size
  storageClassName: gp2-storage-new  # Match this with your PV's storage class